// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsoGj9Elxso9NsCpaIDN2ddXRoLplHa6g',
    appId: '1:124593963785:android:d9ca5037c9a42f521589d8',
    messagingSenderId: '124593963785',
    projectId: 'hibank-test-9a726',
    storageBucket: 'hibank-test-9a726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMum7nHkQ6yQgUnSMuHG4n5rB48ru-Io',
    appId: '1:124593963785:ios:b730ddc64a26c88f1589d8',
    messagingSenderId: '124593963785',
    projectId: 'hibank-test-9a726',
    storageBucket: 'hibank-test-9a726.appspot.com',
    androidClientId: '124593963785-1tssnb8341g4mk52bg42onaifj4663q9.apps.googleusercontent.com',
    iosClientId: '124593963785-luqb4svs28h3nqrdcuvsceschhfqu8vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.hibankTest',
  );

}